sonar.projectKey=cdattg-go
sonar.projectName=cdattg-go
sonar.host.url=https://sonarqube.dataguaviare.com.co

sonar.sources=cdattg_web_frontend/src,cdattg_web_golang
sonar.tests=cdattg_web_frontend/src,cdattg_web_golang
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*_test.go
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.scannerwork/**,**/coverage/**,**/vendor/**,**/*.d.ts,**/sofia_capturas_fallo/**,**/.venv/**
sonar.cpd.exclusions=**/sofia_capturas_fallo/**
sonar.coverage.exclusions=**/main.tsx,**/main.go,**/*_mock.go,**/vite-env.d.ts,**/RegistrosAprendizPanel.tsx,**/FichaCaracterizacionCard.tsx

sonar.javascript.lcov.reportPaths=cdattg_web_frontend/coverage/lcov.info
sonar.go.coverage.reportPaths=cdattg_web_golang/coverage.sonar.out

sonar.sourceEncoding=UTF-8
