import {
  aprendicesPaths,
  aprendizPaths,
  eleccionAprendizPaths,
  asistenciaPaths,
  bienestarPaths,
  DASHBOARD_PATH,
  fichasPaths,
  infraestructuraPaths,
  administracionPaths,
  permisosPaths,
  PERFIL_PATH,
  notificacionesPaths,
  personasPaths,
  programasPaths,
  instructoresPaths,
  instructorPaths,
  bibliotecaPaths,
   personalOperativoApoyoPaths,
   personalAdministrativoPaths,
   contratistasPaths,
   vigilanciaPaths,
   complementariosPaths,
   carnetPaths,
   carnetPerdidaPaths,
 } from '../../routes/paths';
import type { SidebarManifestItem } from './types';

/** Perfiles que administran la formación (media técnica y formación complementaria). */
const ROLES_FORMACION = ['MEDIA TECNICA', 'FORMACION COMPLEMENTARIA'] as const;

/** Quien puede abrir el menú de vigilancia (el borrar visitas va por permiso aparte). */
const ROLES_VIGILANCIA = ['VIGILANTE', 'SUPER VIGILANTE', 'SUPER ADMINISTRADOR', 'ADMINISTRADOR', 'COORDINADOR'] as const;

/** Orden y agrupación del menú lateral (de arriba hacia abajo). */
export const SIDEBAR_MANIFEST: SidebarManifestItem[] = [
  // —— Inicio (accesos directos, sin acordeón) ——
  {
    section: 'Inicio',
    path: DASHBOARD_PATH,
    label: 'Panel principal',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'ADMINISTRADOR', 'BIENESTAR AL APRENDIZ', 'COORDINADOR'],
    alsoVisibleForPermissions: ['VER MI AGENDA'],
    iconKey: 'dashboard',
  },
  {
    section: 'Inicio',
    path: PERFIL_PATH,
    label: 'Mi perfil',
    permission: null,
    iconKey: 'perfil',
  },
  {
    section: 'Inicio',
    path: notificacionesPaths.index,
    label: 'Notificaciones',
    permission: null,
    iconKey: 'notificaciones',
  },
  {
    section: 'Inicio',
    path: aprendizPaths.misInasistencias,
    label: 'Mis inasistencias',
    permission: null,
    rolesRequired: ['APRENDIZ'],
    alsoVisibleForPermissions: ['VER MIS INASISTENCIAS'],
    iconKey: 'asistencia/mis-inasistencias',
  },
  {
    section: 'Carnet',
    path: aprendizPaths.carnetDigital,
    label: 'Carnet digital',
    permission: null,
    rolesRequired: ['APRENDIZ'],
    alsoVisibleForPermissions: ['VER CARNET DIGITAL'],
    iconKey: 'carnet',
  },
  {
    section: 'Carnet',
    path: carnetPerdidaPaths.solicitar,
    label: 'Pérdida de carnet',
    permission: 'SOLICITAR CARNET PERDIDA',
    rolesRequired: ['APRENDIZ'],
    alsoVisibleForPermissions: ['SOLICITAR CARNET PERDIDA'],
    iconKey: 'carnet',
  },
  {
    section: 'Carnet',
    path: carnetPerdidaPaths.revisar,
    label: 'Reposiciones de carnet',
    permission: 'VALIDAR CARNET PERDIDA',
    rolesRequired: ['BIBLIOTECARIO', 'SUPER ADMINISTRADOR'],
    alsoVisibleForPermissions: ['VALIDAR CARNET PERDIDA'],
    iconKey: 'carnet',
  },
  {
    section: 'Carnet',
    path: instructorPaths.validarCarnet,
    label: 'Validar carnet',
    permission: 'VALIDAR CARNET DIGITAL',
    rolesRequired: ['INSTRUCTOR'],
    alsoVisibleForPermissions: ['VALIDAR CARNET DIGITAL'],
    iconKey: 'carnet',
  },
  {
    section: 'Carnet',
    path: bibliotecaPaths.carnets,
    label: 'Carnets regulares',
    permission: 'VER CARNET BIBLIOTECA',
    rolesRequired: ['BIBLIOTECARIO'],
    alsoVisibleForPermissions: ['VER CARNET BIBLIOTECA'],
    iconKey: 'carnet',
  },
  {
    section: 'Carnet',
    path: carnetPaths.configuracion,
    label: 'Configuración carnet',
    permission: 'CONFIGURAR CARNET',
    rolesRequired: ['SUPER ADMINISTRADOR'],
    alsoVisibleForPermissions: ['CONFIGURAR CARNET'],
    iconKey: 'carnet',
  },
  {
    section: 'Inicio',
    path: eleccionAprendizPaths.index,
    label: 'Elección representante',
    permission: null,
    rolesRequired: ['APRENDIZ'],
    alsoVisibleForPermissions: ['VER ELECCION'],
    iconKey: 'eleccion/aprendiz',
  },

  // —— Formación ——
  {
    section: 'Formación',
    path: programasPaths.index,
    label: 'Programas',
    permission: 'VER PROGRAMAS',
    iconKey: 'programas',
  },
  {
    section: 'Formación',
    path: fichasPaths.index,
    label: 'Formación Regular',
    permission: 'VER FICHAS',
    alsoVisibleForRoles: ['INSTRUCTOR'],
    iconKey: 'fichas',
  },
  {
    section: 'Formación',
    path: fichasPaths.mediaTecnica,
    label: 'Media Técnica',
    permission: 'VER FICHAS',
    alsoVisibleForRoles: ['INSTRUCTOR'],
    iconKey: 'fichas',
  },
  {
    section: 'Formación',
    path: fichasPaths.complementaria,
    label: 'Formación Complementaria',
    permission: 'VER FICHAS',
    alsoVisibleForRoles: ['INSTRUCTOR'],
    iconKey: 'fichas',
  },

  // —— Personal ——
  {
    section: 'Personal',
    path: instructoresPaths.index,
    label: 'Instructores',
    permission: 'VER FICHAS',
    iconKey: 'instructores',
  },
  {
    section: 'Personal',
    path: personalOperativoApoyoPaths.index,
    label: 'Personal operativo y de apoyo',
    permission: 'VER PERSONAL OPERATIVO Y DE APOYO',
    iconKey: 'personal-operativo-apoyo',
  },
  {
    section: 'Personal',
    path: personalAdministrativoPaths.index,
    label: 'Personal administrativo',
    permission: 'VER PERSONAL ADMINISTRATIVO',
    iconKey: 'personal-administrativo',
  },
  {
    section: 'Personal',
    path: contratistasPaths.index,
    label: 'Contratistas de prestación de servicios',
    permission: 'VER CONTRATISTAS PRESTACIÓN DE SERVICIOS',
    iconKey: 'contratistas',
  },
  {
    section: 'Personal',
    path: aprendicesPaths.index,
    label: 'Aprendices',
    permission: 'VER APRENDICES',
    iconKey: 'aprendices',
  },
  {
    section: 'Personal',
    path: personasPaths.index,
    label: 'Personas',
    permission: 'VER PERSONAS',
    iconKey: 'personas',
  },

  // —— Asistencia ——
  {
    section: 'Asistencia',
    path: asistenciaPaths.fichas,
    label: 'Tomar asistencia',
    permission: 'VER ASISTENCIA',
    hiddenForRoles: [...ROLES_FORMACION],
    iconKey: 'asistencia',
  },
  {
    section: 'Asistencia',
    path: asistenciaPaths.historial.index,
    label: 'Historial',
    permission: 'VER ASISTENCIA',
    iconKey: 'asistencia/historial',
  },
  {
    section: 'Asistencia',
    path: asistenciaPaths.sesionesSinAsistenciaTomada,
    label: 'Panel de toma de asistencia',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'ADMINISTRADOR', 'COORDINADOR', ...ROLES_FORMACION],
    iconKey: 'asistencia/sin-asistencia',
  },
  {
    section: 'Asistencia',
    path: asistenciaPaths.analisis,
    label: 'Panel analítico de asistencia',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'ADMINISTRADOR', 'COORDINADOR', ...ROLES_FORMACION],
    iconKey: 'asistencia/dashboard',
  },
  {
    section: 'Asistencia',
    path: asistenciaPaths.index,
    label: 'Reporte de asistencia',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'BIENESTAR AL APRENDIZ', ...ROLES_FORMACION],
    iconKey: 'asistencia/dashboard',
  },
  {
    section: 'Asistencia',
    path: asistenciaPaths.cargaRetroactiva,
    label: 'Carga retroactiva',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', ...ROLES_FORMACION],
    iconKey: 'asistencia/historial',
  },
  {
    section: 'Asistencia',
    path: asistenciaPaths.tiposObservacion,
    label: 'Tipos de observación',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR'],
    iconKey: 'asistencia/tipos-observacion',
  },

  // —— FPI ——
  {
    section: 'FPI',
    path: complementariosPaths.betowa,
    label: 'Complementarios (Betowa)',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'ADMINISTRADOR', 'COORDINADOR', 'FPI'],
    iconKey: 'complementarios',
  },
  {
    section: 'FPI',
    path: complementariosPaths.consultarRegistro,
    label: 'Sofía · Fase 1 · Consultar Registro',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'ADMINISTRADOR', 'COORDINADOR', 'FPI'],
    iconKey: 'complementarios',
  },
  {
    section: 'FPI',
    path: complementariosPaths.inscripciones,
    label: 'Sofía · Fase 2 · Programas',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'ADMINISTRADOR', 'COORDINADOR', 'FPI'],
    iconKey: 'complementarios',
  },

  // —— Bienestar ——
  {
    section: 'Bienestar',
    path: bienestarPaths.casos.index,
    label: 'Casos bienestar',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'BIENESTAR AL APRENDIZ', 'INSTRUCTOR', ...ROLES_FORMACION],
    iconKey: 'bienestar/casos',
  },
  {
    section: 'Bienestar',
    path: bienestarPaths.alertasConsecutivas.index,
    label: 'Alertas consecutivas',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'BIENESTAR AL APRENDIZ', 'INSTRUCTOR', ...ROLES_FORMACION],
    iconKey: 'bienestar/casos',
  },

  // —— Infraestructura ——
  {
    section: 'Infraestructura',
    path: infraestructuraPaths.sedes,
    label: 'Sedes',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', ...ROLES_FORMACION],
    iconKey: 'infraestructura/sedes',
  },
  {
    section: 'Infraestructura',
    path: infraestructuraPaths.bloques,
    label: 'Bloques',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', ...ROLES_FORMACION],
    iconKey: 'infraestructura/bloques',
  },
  {
    section: 'Infraestructura',
    path: infraestructuraPaths.pisos,
    label: 'Pisos',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', ...ROLES_FORMACION],
    iconKey: 'infraestructura/pisos',
  },
  {
    section: 'Infraestructura',
    path: infraestructuraPaths.ambientes,
    label: 'Ambientes',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', ...ROLES_FORMACION],
    iconKey: 'infraestructura/ambientes',
  },

  // —— Vigilancia ——
  {
    section: 'Vigilancia',
    path: vigilanciaPaths.porteria,
    label: 'Portería / Acceso',
    permission: 'REGISTRAR ACCESO SEDE',
    rolesRequired: [...ROLES_VIGILANCIA],
    alsoVisibleForPermissions: ['REGISTRAR ACCESO SEDE'],
    iconKey: 'vigilancia/porteria',
  },
  {
    section: 'Vigilancia',
    path: vigilanciaPaths.reporte,
    label: 'Reporte de accesos',
    permission: 'VER ACCESO SEDE',
    rolesRequired: [...ROLES_VIGILANCIA],
    alsoVisibleForPermissions: ['VER ACCESO SEDE'],
    iconKey: 'vigilancia/reporte',
  },
  {
    section: 'Vigilancia',
    path: vigilanciaPaths.ambientes,
    label: 'Ambientes en uso',
    permission: null,
    rolesRequired: [...ROLES_VIGILANCIA],
    alsoVisibleForPermissions: ['REGISTRAR ACCESO SEDE', 'VER ACCESO SEDE'],
    iconKey: 'vigilancia/ambientes',
  },
  {
    section: 'Vigilancia',
    path: vigilanciaPaths.registroPersonas,
    label: 'Registro de personas',
    permission: 'REGISTRAR PERSONA',
    rolesRequired: [...ROLES_VIGILANCIA],
    alsoVisibleForPermissions: ['REGISTRAR PERSONA'],
    iconKey: 'vigilancia/registro',
  },
  {
    section: 'Vigilancia',
    path: vigilanciaPaths.cambiosPendientes,
    label: 'Cambios pendientes',
    permission: 'REGISTRAR PERSONA',
    rolesRequired: [...ROLES_VIGILANCIA],
    alsoVisibleForPermissions: ['REGISTRAR PERSONA'],
    iconKey: 'vigilancia/cambios',
  },

  // —— Administración ——
  {
    section: 'Administración',
    path: administracionPaths.jornadas,
    label: 'Jornadas',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'ADMINISTRADOR', 'COORDINADOR'],
    iconKey: 'administracion/jornadas',
  },
  {
    section: 'Administración',
    path: administracionPaths.diasSinFormacion,
    label: 'Días sin formación',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'ADMINISTRADOR', 'COORDINADOR'],
    iconKey: 'administracion/dias-sin-formacion',
  },
  {
    section: 'Administración',
    path: administracionPaths.configuracionAsistencia,
    label: 'Config. asistencia',
    permission: null,
    rolesRequired: ['SUPER ADMINISTRADOR', 'ADMINISTRADOR', 'COORDINADOR'],
    iconKey: 'administracion/configuracion-asistencia',
  },
  {
    section: 'Administración',
    path: administracionPaths.elecciones,
    label: 'Elecciones aprendices',
    permission: 'GESTIONAR ELECCION',
    rolesRequired: ['SUPER ADMINISTRADOR', 'ADMINISTRADOR', 'COORDINADOR'],
    iconKey: 'administracion/elecciones',
  },
  {
    section: 'Administración',
    path: permisosPaths.index,
    label: 'Permisos y roles',
    permission: 'ASIGNAR PERMISOS',
    iconKey: 'permisos',
  },
];

/** Sección de accesos rápidos (sin acordeón). */
export const SIDEBAR_PRIMARY_SECTION = 'Inicio';
